#!/usr/bin/env zsh

chmod a-x $0

msg="$(git log -n 1 --pretty=format:'%s%n%n%b')"
guilt="$(git guilt HEAD~1 HEAD)"
what="$(curl http://whatthecommit.com/index.txt)"

git commit --no-verify --amend -m $msg$'\n\n'$guilt$'\n\n'$what

chmod a+x $0
